export enum Environment {
  DEVELOPMENT = 'DEVELOPMENT',
  PRODUCTION = 'PRODUCTION',
}

export enum ROLE {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
  SELLER = 'SELLER',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHERS = 'OTHERS',
}

export enum SELLER_STATUS {
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum PACKAGE_STATUS {
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  CANCELLED = 'CANCELLED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum PRODUCT_STATUS {
  AVAILABLE = 'AVAILABLE',
  ORDERED = 'ORDERED',
  SOLD = 'SOLD',
  DONATED = 'DONATED',
}
